---
version: "3.9"

services:
  hugo:
    build:
      context: images/hugo
      args:
        HUGO_VERSION: ${HUGO_VERSION}
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
    command: --watch --baseURL=${NGROK_URL}
    working_dir: /home/hugo/src
    volumes:
      - ./src:/home/hugo/src
    healthcheck:
      test: ["CMD-SHELL", "test -f /home/hugo/src/public/index.html"]
      interval: 1s
      timeout: 1s
      retries: 30

  nginx:
    build:
      context: images/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    depends_on:
      hugo:
        condition: service_healthy
    volumes:
      - ./src/public:/usr/share/nginx/html:ro
    ports:
      - "${NGINX_PORT}:80"

  ngrok:
    profiles:
      - expose
    depends_on:
      - nginx
    image: ngrok/ngrok:alpine
    ports:
      - "${NGROK_PORT}:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http nginx:80 --domain=${NGROK_URL}
