---
version: "3.9"

services:
  cli:
    profiles:
      - cli
    build:
      context: images/hugo
      args:
        HUGO_VERSION: ${HUGO_VERSION}
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
    command: shell
    stdin_open: true
    tty: true
    working_dir: /home/hugo/src
    volumes:
      - ./src:/home/hugo/src
      - hugo-cache:/tmp/hugo
      - hugo-history:/home/hugo/history

  hugo:
    profiles:
      - expose
      - server
    build:
      context: images/hugo
      args:
        HUGO_VERSION: ${HUGO_VERSION}
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
    command: server --buildDrafts ${HUGO_PARAMS}
    working_dir: /home/hugo/src
    volumes:
      - ./src:/home/hugo/src
      - hugo-cache:/tmp/hugo
    ports:
      - "${HUGO_PORT}:1313"
    restart: always

  ngrok:
    profiles:
      - expose
    depends_on:
      - hugo
    image: ngrok/ngrok:alpine
    ports:
      - "${NGROK_PORT}:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http hugo:1313 --domain=${NGROK_URL}

volumes:
  hugo-cache:
  hugo-history: